# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='aprroved_comment',
        ),
    ]
