# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Py', 'Python'), ('Dj', 'Django'), ('Etc', 'Etc')], default='Dj', max_length=3, verbose_name='Category'),
        ),
    ]
