# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 15:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_aprroved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='CONTENT'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
