# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161219_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url_slug',
            new_name='slug',
        ),
    ]
