# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170102_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='my_comment',
        ),
    ]
